### ISSUE TITLE
Fixed Header and Sidebar

### ISSUE THREAD

**Issue by omastroberti** [dcasia/collapsible-resource-manager#133]
Hi, great work! does your menu is fixed is scrolled down as Nova default? Thanks

**Comment by milewski** [comment]
It is fixed, and if you have too many items then it scrolls

**Comment by omastroberti** [comment]
thanks

**Comment by mathieufrh** [comment]
Hello and thank you @milewski for this package, very well crafted, as for all your other nova packages. 

And don't know what you guys mean by "fixed". Is it fixed on the page so that it disappears when scrolling down or is it fixed for the user so that it is always visible ? 

For me navbar and resources icons are disappearing when scrolling down. Is there an easy way to avoid this ?

**Comment by omastroberti** [comment]
@mathieufrh my question was intented to this: 

![image](https://github.com/user-attachments/assets/95ea082f-79ea-4708-b28d-899dc81b0f0f)

**Comment by mathieufrh** [comment]
Well, unfortunately it is  not fixed. And there is no option to make it fix. Maybe i the future, that would be nice.
